"""Safe defaults used when configuration is missing or corrupted."""


# ATEM Defaults
DEFAULT_ATEM_HOST = "192.168.1.100"
DEFAULT_ATEM_PORT = 21124
DEFAULT_ATEM_TIMEOUT = 5.0

# Connection Defaults
DEFAULT_RECONNECT_ATTEMPTS = 5
DEFAULT_RECONNECT_DELAY = 2.0
MAX_RECONNECT_DELAY = 30.0

# Switching Defaults
DEFAULT_INTERVAL_POOL = [30.0, 60.0, 90.0, 120.0, 150.0]
DEFAULT_SWITCH_MODE = "balanced_random"
DEFAULT_SAFE_CAMERA = 1
DEFAULT_MIN_HOLD_DURATION = 10.0
DEFAULT_COOLDOWN_SECONDS = 5.0
DEFAULT_LOCK_DURATION = 300.0

# Transition Defaults
DEFAULT_TRANSITION_MODE = "cut"
DEFAULT_MIX_DURATION_MS = 300
MIN_MIX_DURATION_MS = 1
MAX_MIX_DURATION_MS = 5000

# Monitoring Defaults
MONITORING_INTERVAL_MS = 500  # Poll device state every 500ms
ENGINE_TICK_INTERVAL_MS = 100  # Run state machine every 100ms
STATS_SYNC_INTERVAL_SECONDS = 30  # Sync stats to DB every 30s

# Recovery Defaults
ZERO_ELIGIBLE_RETRY_SECONDS = 5  # Retry if no eligible inputs
STALE_STATE_TIMEOUT_SECONDS = 30  # WebSocket connection stale after 30s

# Limits
MAX_EVENT_LOG_ENTRIES = 1000
MAX_CAMERA_COUNT = 32
MIN_CAMERA_COUNT = 1

# Validator Defaults
DEFAULT_MIN_PORT = 1024
DEFAULT_MAX_PORT = 65535
DEFAULT_MAX_DURATION_MS = 5000
DEFAULT_MAX_SECONDS = 600.0
DEFAULT_MAX_WEIGHT = 10.0
DEFAULT_MIN_WEIGHT = 0.1
